export const routes = [
  { path: '/', source: 'index.html', label: 'Home' },
  { path: '/index', source: 'index.html', label: 'Home' },
  { path: '/home-2', source: 'home-2.html', label: 'Home 2' },
  { path: '/about', source: 'about.html', label: 'About' },
  { path: '/blog', source: 'blog.html', label: 'Blog' },
  { path: '/case-studies', source: 'case-studies.html', label: 'Case Studies' },
  { path: '/contact', source: 'contact.html', label: 'Contact' },
  { path: '/detail_blog', source: 'detail_blog.html', label: 'Blog Detail' },
  { path: '/detail_case-study', source: 'detail_case-study.html', label: 'Case Study Detail' },
  { path: '/detail_service', source: 'detail_service.html', label: 'Service Detail' },
  { path: '/faqs', source: 'faqs.html', label: 'FAQs' },
  { path: '/privacy-policy', source: 'privacy-policy.html', label: 'Privacy Policy' },
  { path: '/products', source: 'products.html', label: 'Products' },
  { path: '/services', source: 'services.html', label: 'Services' },
  { path: '/starter-page', source: 'starter-page.html', label: 'Starter Page' },
  { path: '/401', source: '401.html', label: 'Protected Page' },
  { path: '/404', source: '404.html', label: 'Not Found' },
  { path: '/utility-pages/changelog', source: 'utility-pages/changelog.html', label: 'Changelog' },
  { path: '/utility-pages/instructions', source: 'utility-pages/instructions.html', label: 'Instructions' },
  { path: '/utility-pages/licenses', source: 'utility-pages/licenses.html', label: 'Licenses' },
  { path: '/utility-pages/style-guide', source: 'utility-pages/style-guide.html', label: 'Style Guide' },
]
